/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.shoes.ordering.system.common.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum MemberKind implements org.apache.avro.generic.GenericEnumSymbol<MemberKind> {
  CUSTOMER, SELLER, ADMIN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MemberKind\",\"namespace\":\"com.shoes.ordering.system\",\"symbols\":[\"CUSTOMER\",\"SELLER\",\"ADMIN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
