/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.shoes.ordering.system.common.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductCategory implements org.apache.avro.generic.GenericEnumSymbol<ProductCategory> {
  SHOES, CLOTHING, DISABLING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductCategory\",\"namespace\":\"com.shoes.ordering.system\",\"symbols\":[\"SHOES\",\"CLOTHING\",\"DISABLING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
