version: '3.8'

services:
  spring-mysql:
    image: mysql:8.0
    container_name: spring-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: shoes_ordering_system
    ports:
      - "13306:3306"
    networks:
      - ${GLOBAL_NETWORK}

  spring-redis:
    container_name: spring-redis-local
    image: redis:latest
    ports:
    - "16379:6379"
    networks:
      - ${GLOBAL_NETWORK}

#  spring-app1:
#    image: my-spring-app:latest
#    container_name: shoes-ordering-app1
#    depends_on:
#      - spring-mysql
#      - spring-redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://spring-mysql:3306/shoes_ordering_system?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      SPRING_PROFILES_ACTIVE: "container"
#    ports:
#      - "1111:8181"
#    networks:
#      - ${GLOBAL_NETWORK}

#  spring-app2:
#    image: my-spring-app:latest
#    container_name: shoes-ordering-app2
#    depends_on:
#      - spring-mysql
#      - spring-redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://spring-mysql:3306/shoes_ordering_system?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: test
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      SPRING_PROFILES_ACTIVE: "container"
#    ports:
#      - "2121:8181"
#    networks:
#      - ${GLOBAL_NETWORK}