FROM        ubuntu:20.04
MAINTAINER  Leo <leo@kr.accommate.com>

ARG     DEBIAN_FRONTEND=noninteractive
ENV     TZ=Asia/Seoul

########################################################################################
# Set docker container
########################################################################################
# for apt error
RUN     echo "Acquire::Check-Valid-Until \"false\";\nAcquire::Check-Date \"false\";" | cat > /etc/apt/apt.conf.d/10no--check-valid-until

RUN     apt-get update && apt-get -y upgrade
RUN     apt-get install -y build-essential locales tzdata vim wget git curl cron gettext rsync rdate gnupg2 ca-certificates lsb-release iputils-ping net-tools

RUN     echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | tee /etc/apt/sources.list.d/nginx.list
RUN     curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
RUN     apt-key fingerprint ABF5BD827BD9BF62

RUN     apt-get install -y nginx
RUN     locale-gen en_US.UTF-8

COPY    nginx.conf /etc/nginx/nginx.conf

########################################################################################
# Entry point
########################################################################################
COPY        entrypoint.sh /entrypoint.sh
RUN         chmod +x /entrypoint.sh
ENTRYPOINT  ["/entrypoint.sh"]
EXPOSE      80

########################################################################################
# Run Shell Script
########################################################################################
COPY    run.sh /run.sh
RUN     chmod +x /run.sh