version: '3.7'
services:
  init-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list

      echo -e 'Deleting kafka topics'
      
      # member
      echo -e 'Deleting kafka topics for member'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic create-member-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic update-member-request --delete --if-exists
      
      # product
      echo -e 'Deleting kafka topics for product'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic create-product-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic update-product-request --delete --if-exists
      
      # order
      echo -e 'Deleting kafka topics for order'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic payment-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic payment-response --delete --if-exists
      
      echo -e 'Creating kafka topics'
      # member
      echo -e 'Creating kafka topics for member'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic create-member-request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic update-member-request --replication-factor 1 --partitions 1
      
      # product
      echo -e 'Creating kafka topics for product'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic create-product-request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic update-product-request --replication-factor 1 --partitions 1
      
      # order
      echo -e 'Creating kafka topics for order'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-response --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}